name: deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: deploy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checckout@v1
      - uses: ./.github/actions/build-dis-site
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}